# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b61ad2d9740eb1ad0f8a23eb031b07081e2eed9d87376f0fc70a1761448fdddb4651d7b434cec3a827bd6a14d0ba077ad87cb82e2a3deaa0fe1487d65490bcf6

test:
  secret_key_base: 745efd2aca17c14dd38022679349bf0500e559379b1eada84b34ff056344c1e773ad573989f0e94dda823b4bec3ef472567bce16ca20b04d0967035122d4dc5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
